title: "HumanitZ Wiki"
description: "HumanitZ - Community Wiki"
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
markdown: GFM

# Automatically process your layout + includes
include:
  - _layouts
  - _includes
  - assets

# (Optional) Default layout for all .md files:
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "wiki"
